openapi: "3.0.0"
info:
  title: "Interfaces"
  version: "1.0.0"
servers:
  - url: http://{hostname}/api/v1
    variables:
      hostname:
        default: localhost:8080
tags:
  - name: demo
    description: |
      The series of APIs for demo use

paths:
  /demo:
    get:
      operationId: GetDemo
      tags: [demo]
      summary: Get demo api
      parameters:
        - in: query
          schema: { type: string }
          name: firstname
          required: false
          description: The firstname of the user
      responses:
        "200":
          description: "successful response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetDemoResponse"
        "500":
          $ref: "#/components/responses/ErrorInternal"

components:
  parameters:
    pathWithID:
      in: path
      schema: { type: number }
      name: id
      required: true
      description: The id to look up
    Authorization:
      in: header
      name: X-Auth
      schema:
        type: string
      required: true

  schemas:
    DemoModel:
      $ref: "schemas/demo/demo.yml"

    GetDemoResponse:
      $ref: "#/components/schemas/DemoModel"

  responses:
    # API Gateway does not support response definitions here for '200' responses
    # It ignores error (non-200) responses
    ErrorInternal:
      $ref: "schemas/common_models.yml#/responses/ErrorInternal"
    ErrorUnauthenticated:
      $ref: "schemas/common_models.yml#/responses/ErrorUnauthenticated"
    ErrorUnauthorised:
      $ref: "schemas/common_models.yml#/responses/ErrorUnauthorised"
    ErrorNotFound:
      $ref: "schemas/common_models.yml#/responses/ErrorNotFound"
    ErrorBadRequest:
      $ref: "schemas/common_models.yml#/responses/ErrorBadRequest"
    ErrorConflict:
      $ref: "schemas/common_models.yml#/responses/ErrorConflict"
